### ISSUE TITLE
Bug fatal for https://bl.iro.bl.uk/concern/datasets/2fa13eb5-1767-469b-b4c0-d9d518bfc1b3 (and others)

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/britishlibrary#144]
I think we have an edge case: https://bl.iro.bl.uk/concern/datasets/2fa13eb5-1767-469b-b4c0-d9d518bfc1b3 that tickles a bug which I _think_ is part of the theming stuff?

```
F, [2022-05-13T18:14:25.822054 #1] FATAL -- : [81a889c7171a3a27248563e57e38106f]
F, [2022-05-13T18:14:25.822122 #1] FATAL -- : [81a889c7171a3a27248563e57e38106f] ActionView::Template::Error (wrong number of arguments (given 1, expected 2)):
F, [2022-05-13T18:14:25.822274 #1] FATAL -- : [81a889c7171a3a27248563e57e38106f]     16:     xml.author { xml.name(document.to_semantic_values[:author].first) }
[81a889c7171a3a27248563e57e38106f]     17:   end
[81a889c7171a3a27248563e57e38106f]     18:
[81a889c7171a3a27248563e57e38106f]     19:   with_format("html") do
[81a889c7171a3a27248563e57e38106f]     20:     xml.summary "type" => "html" do
[81a889c7171a3a27248563e57e38106f]     21:       xml.text! render_document_partial(document,
[81a889c7171a3a27248563e57e38106f]     22:       :index,
F, [2022-05-13T18:14:25.822310 #1] FATAL -- : [81a889c7171a3a27248563e57e38106f]
F, [2022-05-13T18:14:25.822336 #1] FATAL -- : [81a889c7171a3a27248563e57e38106f] app/helpers/blacklight/blacklight_helper_behavior.rb:334:in `with_format'
[81a889c7171a3a27248563e57e38106f] app/controllers/application_controller.rb:162:in `inject_theme_views'
[81a889c7171a3a27248563e57e38106f] app/middleware/no_cache_middleware.rb:11:in `call'
```

The object loads fine if format is not html: https://bl.iro.bl.uk/concern/datasets/2fa13eb5-1767-469b-b4c0-d9d518bfc1b3.json~~~~

**Comment by cziaarm** [comment]
Fixed possibly helped by removal of two awkward file_sets see #143
